# Generated by Django 2.2 on 2020-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200207_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=20, verbose_name='Электронная почта')),
                ('text', models.TextField(max_length=500, verbose_name='Текст сообщения')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published'],
                'verbose_name_plural': 'сообщения',
                'verbose_name': 'сообщение',
            },
        ),
    ]
