# Generated by Django 2.2 on 2020-02-28 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200227_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20, message='Введите Ваше имя')], verbose_name='Имя отправителя'),
        ),
    ]
