# Generated by Django 3.0.4 on 2020-04-06 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200228_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Введите коректный адрес электронной почты')], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(20, message='Введите Ваше имя')], verbose_name='Имя отправителя'),
        ),
    ]
