# Generated by Django 2.2 on 2020-06-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200406_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='media',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на медиа'),
        ),
    ]
