# Generated by Django 2.2 on 2020-06-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Пользователи телеграм')),
            ],
            options={
                'verbose_name': 'пользователи телеграмм',
            },
        ),
    ]
