# Generated by Django 2.2 on 2020-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_tusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusers',
            name='user',
            field=models.CharField(default='', max_length=100, verbose_name='ник'),
            preserve_default=False,
        ),
    ]
