# Generated by Django 2.2 on 2020-06-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_tusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusers',
            name='user_id',
            field=models.IntegerField(verbose_name='ID Пользователя телеграм'),
        ),
    ]
