# Generated by Django 2.2 on 2020-06-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200623_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusers',
            name='subscription',
            field=models.BooleanField(default=True, verbose_name='подписка'),
            preserve_default=False,
        ),
    ]
