# Generated by Django 2.2 on 2020-06-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200624_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tusers',
            options={'verbose_name': 'пользователь телеграмм', 'verbose_name_plural': 'пользователи телеграмм'},
        ),
        migrations.AlterField(
            model_name='tusers',
            name='subscription',
            field=models.BooleanField(blank=True, null=True, verbose_name='подписка'),
        ),
    ]
