# Generated by Django 2.2 on 2020-07-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20200624_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, editable=False, null=True, verbose_name='Текст новости')),
                ('url_source', models.URLField(blank=True, max_length=1000, null=True, verbose_name='ссылка на ресурс')),
                ('media', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на медиа')),
            ],
            options={
                'verbose_name': 'новости Саратова',
                'verbose_name_plural': 'новости Саратова',
                'ordering': ['-published'],
            },
        ),
    ]
